name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  calls-reusable:
    uses: jburns24/test-actions/.github/workflows/getting-started.yml@main
    with:
      input-string: 'Input from caller workflow'
