name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  calls-reusable:
    uses: jburns24/test-actions/.github/workflows/getting-started.yml@main
    with:
      input-string: 'Input from caller workflow'

  finalize:
    runs-on: ubuntu-latest
    needs: calls-reusable
    steps:
      - name: Print status of calls-reusable
        run: echo ${{ needs.calls-reusable.result }}
