# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  workflow_dispatch:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      helloWorld: ${{ steps.generateOutput.outputs.helloWorld }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: generate outputs
      #   uses: actions/checkout@v4
      - name: Generate Artifact
        uses: jburns24/test-actions@main
        with:
          string: 'Passed in value ${{ secrets.PASSWORD }}'
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: See output from artifact
        run: cat hello.txt 
      - name: Set output from artifact
        id: generateOutput
        run: echo "helloWorld=$(cat hello.txt)" >> $GITHUB_OUTPUT
  matrix-job:
    needs: simple
    runs-on: ubuntu-latest
    strategy:
      matrix:
        numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Cat the artifact
        run: echo $(cat $GITHUB_WORKSPACE/hello.txt)-${{ matrix.numbers }}
      - name: Cat the outputs
        run: echo ${{ needs.simple.outputs.helloWorld }}-${{ matrix.numbers }}
      
